// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Area struct {
	ID               int32
	Nombre           string
	Admitemovermesas bool
	Admitefumadores  bool
}

type Cliente struct {
	ID        int32
	Nombre    string
	Direccion sql.NullString
	Nit       string
}

type Cuentum struct {
	Mesa        int32
	Numcuenta   int32
	Estacerrada bool
	Numpersonas int32
	Total       string
}

type Empleado struct {
	ID     int32
	Nombre string
	Puesto int32
	Area   sql.NullInt32
}

type Encuestum struct {
	Empleado        int32
	Cliente         int32
	Gradoamabilidad int32
	Gradoexactitud  int32
	Fecha           time.Time
}

type Estadospedido struct {
	ID     int32
	Nombre string
}

type Factura struct {
	Numfactura int32
	Fecha      time.Time
	Cuenta     int32
	Cliente    int32
}

type Itemmenu struct {
	ID             int32
	Nombre         string
	Descripcion    string
	Preciounitario string
	Categoria      int32
}

type Itemmenucategorium struct {
	ID     int32
	Nombre string
}

type Mesa struct {
	ID        int32
	Area      int32
	Capacidad int32
}

type Pago struct {
	Tipo    int32
	Monto   float64
	Factura int32
}

type Pedido struct {
	ID       int32
	Fecha    time.Time
	Estado   int32
	Cantidad int32
	Cuenta   int32
	Item     int32
}

type Puesto struct {
	ID           int32
	Nombrepuesto sql.NullString
}

type Queja struct {
	Cliente  int32
	Gravedad int32
	Motivo   string
	Fecha    time.Time
	Empleado sql.NullInt32
	Item     sql.NullInt32
}

type Tipopago struct {
	ID     int32
	Nombre string
}

type Tipousuario struct {
	ID     int32
	Nombre string
}

type Usuario struct {
	Nombre     string
	Contraseña string
	Tipo       int32
	Empleado   int32
}
