// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package ratatuilledb

import (
	"database/sql"
	"time"
)

type Area struct {
	ID               int32
	Nombre           string
	Admitemovermesas bool
	Admitefumadores  bool
}

type Cliente struct {
	ID        int32
	Nombre    sql.NullString
	Direccion sql.NullString
	Nit       sql.NullString
}

type Cuentum struct {
	Mesa        int32
	Numcuenta   int32
	Estacerrada sql.NullBool
	Numpersonas sql.NullInt32
}

type Empleado struct {
	ID     int32
	Nombre sql.NullString
	Puesto sql.NullInt32
	Area   sql.NullInt32
}

type Encuestum struct {
	Empleado        sql.NullInt32
	Cliente         sql.NullInt32
	Gradoamabilidad sql.NullInt32
	Gradoexactitud  sql.NullInt32
	Fecha           sql.NullTime
}

type Estadospedido struct {
	ID     int32
	Nombre sql.NullString
}

type Factura struct {
	Numfactura int32
	Fecha      sql.NullTime
	Cuenta     sql.NullInt32
	Cliente    sql.NullInt32
}

type Itemmenu struct {
	ID             int32
	Nombre         sql.NullString
	Descripcion    sql.NullString
	Preciounitario sql.NullString
	Categoria      sql.NullInt32
}

type Itemmenucategorium struct {
	ID     int32
	Nombre sql.NullString
}

type Mesa struct {
	ID        int32
	Area      sql.NullInt32
	Capacidad sql.NullInt32
}

type Pago struct {
	Tipo       sql.NullInt32
	Monto      sql.NullFloat64
	Numfactura sql.NullInt32
}

type Pedido struct {
	ID       int32
	Fecha    sql.NullTime
	Estado   sql.NullInt32
	Cantidad sql.NullInt32
	Cuenta   sql.NullInt32
	Item     sql.NullInt32
}

type Puesto struct {
	ID           int32
	Nombrepuesto sql.NullString
}

type Queja struct {
	Cliente  int32
	Gravedad int32
	Motivo   string
	Fecha    time.Time
	Empleado sql.NullInt32
	Item     sql.NullInt32
}

type Tipopago struct {
	ID     int32
	Nombre sql.NullString
}

type Tipousuario struct {
	ID     int32
	Nombre sql.NullString
}

type Usuario struct {
	Nombre     string
	Contraseña string
	Tipo       int32
}
